#
# Copyright 2016 Roger Pueyo Centelles <roger.pueyo@guifi.net>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for GRE tunnels (Generic Routing Encapsulation (GRE)  RFC2784)
LUCI_DEPENDS:=+gre

PKG_MAINTAINER:=Jan Betik <jan.betik@svine.su>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
